import os

GCP_PROJECT = os.getenv("GCP_PROJECT")
LOGS_COLLECTION_NAME = os.getenv("LOGS_COLLECTION_NAME")
SCANS_BUCKET_NAME = os.getenv("SCANS_BUCKET_NAME")
SERVICE_ACCOUNT_KEYFILE = os.getenv("SERVICE_ACCOUNT_KEYFILE")
