version: "3.3"

services:
  reporter:
    container_name: auspex_reporter
    image: auspex/reporter:latest
    build:
      context: .
      dockerfile: ./reporter/Dockerfile
    env_file: .env
    secrets:
      - gcp_credentials
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_credentials
    ports:
      - 8090:80
      - 5690:5678
    networks:
      - default

  restapi:
    image: auspex/restapi:latest
    container_name: auspex_restapi
    build:
      context: .
      dockerfile: ./restapi/Dockerfile
    env_file: .env
    ports:
      - 8091:80
      - 5691:5678
    networks:
      - default

  scanner:
    image: auspex/scanner:latest
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: "1024M"
    container_name: auspex_scanner
    build:
      context: ./
      dockerfile: ./scanner/Dockerfile
    env_file: .env
    secrets:
      - snyk_token
      - gcp_credentials
      - scanner_key
    environment:
      SNYK_TOKEN_FILE: /run/secrets/snyk_token
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/scanner_key
      SCANNER_KEY_FILE: /run/secrets/scanner_key
    ports:
      - 8092:80
      - 5692:5678
    networks:
      - default

secrets:
  snyk_token:
    file: .keys/snyk_token
  gcp_credentials:
    file: .keys/reporter_local.json
  scanner_key:
    file: .keys/scanner.json
