steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  env:
    - DOCKER_BUILDKIT=1
  args: ['build', '-t', '${_IMAGE_NAME}', '-f', 'scanner/Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']
# Deploy container image to Cloud Run
# TODO: replace with script or bake deploy_scanner.sh into this file
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    '${_SERVICE_NAME}',
    '--image',
    '${_IMAGE_NAME}',
    '--port',
    '${_PORT}',
    '--memory',
    '${_MEMORY}',
    '--cpu',
    '${_CPU}',
    '--region',
    '${_SERVICE_REGION}',
    '--project',
    '${PROJECT_ID}',
    '--set-env-vars',
    'COLLECTION_SCANS=${_COLLECTION_SCANS},BUCKET_SCANS=${_BUCKET_SCANS},URL_SCANNER_SNYK=${_URL_SCANNER_SNYK}',
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'services',
    'update-traffic',
    '${_SERVICE_NAME}',
    '--to-latest',
    '--region',
    '${_SERVICE_REGION}',
  ]
tags:
  - scanner
images:
  - ${_IMAGE_NAME}
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#dynamic_substitutions
substitutions:
    _IMAGE_NAME: 'eu.gcr.io/${PROJECT_ID}/auspex/scanner'
    _SERVICE_NAME: 'scanner'
    _URL_SCANNER_SNYK: https://scanner-snyk-qk6stf4ejq-lz.a.run.app
    _PORT: "80"
    _MEMORY: "1Gi"
    _CPU: "1"
options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
