steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  env:
    - DOCKER_BUILDKIT=1
  args: ['build', '-t', '${_IMAGE_NAME}', '-f', 'restapi/Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    '${_SERVICE_NAME}',
    '--image',
    '${_IMAGE_NAME}',
    '--allow-unauthenticated',
    '--port',
    '${_PORT}',
    '--region',
    '${_SERVICE_REGION}',
    '--set-env-vars',
    'URL_SCANNER=${_URL_SCANNER},URL_REPORTER=${_URL_REPORTER}',
    '--project',
    '${PROJECT_ID}',
]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'services',
    'update-traffic',
    '${_SERVICE_NAME}',
    '--to-latest',
    '--region',
    '${_SERVICE_REGION}',
  ]
timeout: 1200s
tags:
  - restapi
images:
- ${_IMAGE_NAME}
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#dynamic_substitutions
substitutions:
    _IMAGE_NAME: 'eu.gcr.io/${PROJECT_ID}/auspex/restapi'
    _SERVICE_NAME: 'restapi'
    _PORT: "80"
    _SERVICE_REGION: "europe-north1"
    _URL_SCANNER: https://scanner-qk6stf4ejq-lz.a.run.app
    _URL_REPORTER: https://reporter-qk6stf4ejq-lz.a.run.app
options:
    dynamic_substitutions: true
