steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  env:
    - DOCKER_BUILDKIT=1
  args: ['build', '-t', '${_IMAGE_NAME}', '-f', 'scanner/Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']
# Deploy container image to Cloud Run
# TODO: replace with script or bake deploy_scanner.sh into this file
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    '${_SERVICE_NAME}',
    '--image',
    '${_IMAGE_NAME}',
    '--port',
    '${_PORT}',
    '--memory',
    '${_MEMORY}',
    '--cpu',
    '${_CPU}',
    '--region',
    '${_SERVICE_REGION}',
    '--concurrency',
    '1',
    '--set-env-vars',
    'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT},SNYK_TOKEN_FILE=${_SNYK_TOKEN_FILE},GOOGLE_APPLICATION_CREDENTIALS=${_SCANNER_CREDENTIALS}',
    '--set-secrets',
    '${_SNYK_TOKEN_FILE}=${_SECRET_SNYK_TOKEN},${_SCANNER_CREDENTIALS}=${_SECRET_CREDENTIALS}',
    '--project',
    '${PROJECT_ID}',
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'services',
    'update-traffic',
    '${_SERVICE_NAME}',
    '--to-latest',
    '--region',
    '${_SERVICE_REGION}',
  ]
tags:
  - scanner_snyk
images:
- ${_IMAGE_NAME}
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#dynamic_substitutions
substitutions:
    _IMAGE_NAME: 'eu.gcr.io/${PROJECT_ID}/auspex/scanner-snyk'
    _SERVICE_NAME: 'scanner-snyk'
    _SNYK_TOKEN_FILE: /run/secrets/SNYK_TOKEN_FILE
    _SCANNER_CREDENTIALS: /run/secrets/gcpcreds/SCANNER_CREDENTIALS
    _PORT: "80"
    # NOTE: MUST have 2 cores if using 8 GiB (Cloud Run restriction)
    #
    # TODO: determine if we have any images that require 8GB RAM
    #       For context, auspex/reporter with a virtual size of 2GB
    #       requires 8GB ram to scan (due to Cloud Run in-memory filesystem)
    _MEMORY: "8Gi"
    _CPU: "2"
options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
