steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  env:
    - DOCKER_BUILDKIT=1
  args: ['build', '-t', '${_IMAGE_NAME}', '-f', 'setup/Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']
# Run the setup as a one-off job
- name: 'eu.gcr.io/${PROJECT_ID}/auspex/setup'
  env:
    - COLLECTION_REPORTS=${_COLLECTION_REPORTS}
    - COLLECTION_SCANS=${_COLLECTION_SCANS}
    - BUCKET_SCANS=${_BUCKET_SCANS}
    - BUCKET_REPORTS=${_BUCKET_REPORTS}
    - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
    - SERVICE_REGION=${_SERVICE_REGION}
timeout: 1200s
tags:
  - setup
images:
- ${_IMAGE_NAME}
substitutions:
  _IMAGE_NAME: 'eu.gcr.io/${PROJECT_ID}/auspex/setup'
options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
