steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  env:
    - DOCKER_BUILDKIT=1
  args: ['build', '-t', '${_IMAGE_NAME}', '-f', 'setup/Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    '${_SERVICE_NAME}',
    '--image',
    '${_IMAGE_NAME}',
    '--allow-unauthenticated',
    '--port',
    '${_PORT}',
    '--region',
    '${_SERVICE_REGION}',
    '--set-env-vars',
    'COLLECTION_REPORTS=auspex-reports,COLLECTION_SCANS=auspex-scans,BUCKET_SCANS=auspex-scans,BUCKET_REPORTS=auspex-reports',
    '--project',
    '${PROJECT_ID}',
]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'services',
    'update-traffic',
    '${_SERVICE_NAME}',
    '--to-latest',
    '--region',
    '${_SERVICE_REGION}',
  ]
timeout: 1200s
images:
- ${_IMAGE_NAME}

# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#dynamic_substitutions
substitutions:
    _IMAGE_NAME: 'eu.gcr.io/${PROJECT_ID}/auspex/setup'
    _SERVICE_NAME: 'setup'
    _PORT: "80"
    _SERVICE_REGION: "europe-north1"
options:
    dynamic_substitutions: true
